### ISSUE TITLE
IndexError: index out of range

### ISSUE THREAD

**Issue by rshravan** [mds1/path-planning#1]
Hi, 

When I am using "useMovingGoals = True" mode I am getting "IndexError: index out of range" error. Any idea? No other changes were made. More details:
Traceback (most recent call last):
  File "main_hdstar.py", line 52, in <module>
    path = fcn.findPath(L)
  File "/Users/rs/Documents/ik/Work/Development/github-repos/path-planning/all_functions.py", line 629, in findPath
    path = L[0].computeShortestPath(path,False)
  File "/Users/rs/Documents/ik/Work/Development/github-repos/path-planning/all_functions.py", line 1141, in computeShortestPath
    kOld1, kOld2, u = self.pop_node()
  File "/Users/rs/Documents/ik/Work/Development/github-repos/path-planning/all_functions.py", line 953, in pop_node
    key1, key2, u = heapq.heappop(CL.U)
IndexError: index out of range

**Comment by mds1** [comment]
There was a bug in the movingGoals function that resulted in the goal being placed within an obstacle, and thus making it unreachable. The "index out of range" error is a result of this, as it indicates a path does not exist after searching every node in the queue. I will fix this and commit the changes later today.

**Comment by mds1** [comment]
Changes have been committed, and the issue should be resolved now.
